#!/usr/bin/env python
#
# https://github.com/renefritze/clangquill documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import sys
import os
from pathlib import Path

this_dir = Path(__file__).resolve().parent
root_dir = (this_dir / '..').resolve()
sys.path.insert(0, str(root_dir))
sys.path.insert(0, str(this_dir))

import clangquill

# The bundled-libclang pin (single source of truth in tools/ci/llvm-version.txt);
# its major is both the toolchain-search ceiling and the C++26 dogfood threshold.
LIBCLANG_PIN_MAJOR = int(
    (root_dir / "tools" / "ci" / "llvm-version.txt").read_text().strip().split(".")[0]
)

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', "autoapi.extension", "myst_nb",
                  "sphinx.ext.coverage",
    "sphinx.ext.autosummary",
    "sphinx.ext.linkcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    # Dogfood: clangquill documents its own C++ IR data model. The extension
    # parses the headers below at build time into the generated `cpp_api/`
    # pages. It degrades to a no-op when the core was built without libclang.
    "clangquill.sphinx_ext"]

# clangquill self-documentation: the public C++ IR/parser/store headers under
# src/cpp. Paths are relative to this srcdir (docs/). The parser headers pull in
# <clang-c/Index.h> and the store headers <sqlite3.h>; sqlite3.h is on the
# default /usr/include search path, but clang-c lives under the LLVM include dir
# (e.g. /usr/lib/llvm-18/include), so it must be added explicitly or libclang
# fails to resolve it -- and a `-W` docs build turns that diagnostic into an
# error. We discover it the same way cmake/FindLibClang.cmake does, via
# `llvm-config --includedir`.
clangquill_input = [
    "../src/cpp/core/*.hpp",
    "../src/cpp/model/*.hpp",
    "../src/cpp/hash/*.hpp",
    "../src/cpp/parser/*.hpp",
    "../src/cpp/store/*.hpp",
]
clangquill_include_dirs = ["../src/cpp"]


def _llvm_includedir():
    """Return the LLVM include dir holding ``clang-c/Index.h``, or None.

    Mirrors ``cmake/FindLibClang.cmake``: honor ``LibClang_ROOT`` (set by the
    clang-22 dogfood CI job), then ask the ``llvm-config`` matching the linked
    backend's major version, then fall back to an unversioned/any ``llvm-config``
    on PATH. Only a directory that actually contains ``clang-c/Index.h`` is
    returned, so a version mismatch never yields a bogus include path.
    """
    import shutil  # noqa: PLC0415
    import subprocess  # noqa: PLC0415

    from clangquill._libclang import libclang_major  # noqa: PLC0415

    def _has_clang_c(directory):
        return bool(directory) and os.path.isfile(
            os.path.join(directory, "clang-c", "Index.h")
        )

    # 1. LibClang_ROOT/include (the CI dogfood job pins the prefix this way).
    root = os.environ.get("LibClang_ROOT")
    if root and _has_clang_c(os.path.join(root, "include")):
        return os.path.join(root, "include")

    # 2. llvm-config, preferring the one matching the linked libclang major.
    candidates = []
    major = libclang_major()
    if major:
        candidates.append(f"llvm-config-{major}")
    candidates += ["llvm-config", *(f"llvm-config-{v}" for v in range(LIBCLANG_PIN_MAJOR, 16, -1))]
    seen = set()
    for exe in candidates:
        if exe in seen:
            continue
        seen.add(exe)
        path = shutil.which(exe)
        if not path:
            continue
        try:
            out = subprocess.run(  # noqa: S603
                [path, "--includedir"], capture_output=True, text=True, check=True
            )
        except (OSError, subprocess.CalledProcessError):
            continue
        includedir = out.stdout.strip()
        if _has_clang_c(includedir):
            return includedir
    return None


_llvm_inc = _llvm_includedir()
clangquill_compile_args = [f"-I{_llvm_inc}"] if _llvm_inc else []
clangquill_output_dir = "cpp_api"
clangquill_std = "c++20"

# Optionally dogfood newer-standard features. The C++23/26 showcase header only
# parses on a recent libclang, so we gate it on the linked backend's version:
# on an older toolchain (e.g. Read the Docs' Ubuntu libclang 18) the page is
# omitted and the build stays warning-free rather than failing.
from clangquill._libclang import libclang_major  # noqa: E402

if (libclang_major() or 0) >= LIBCLANG_PIN_MAJOR:
    clangquill_std = "c++26"
    clangquill_input = [*clangquill_input, "examples/cpp23_features.hpp"]
# this enables:
# substitutions-with-jinja2, direct-latex-math and definition-lists
# ref: https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "deflist",
    "html_image",
    "colon_fence",
    "smartquotes",
    "replacements",
    "substitution",
]
myst_url_schemes = ["http", "https", "mailto"]
# auto genereated link anchors
myst_heading_anchors = 2
import substitutions  # noqa

myst_substitutions = substitutions.myst_substitutions
nb_execution_mode = "cache"
nb_execution_timeout = 240  # there is an interpolation test
# print tracebacks to stdout
nb_execution_show_tb = True
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.ipynb': 'myst-nb',
    '.md': 'myst-nb',
}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'clangquill'
copyright = "2023, René Fritze"
author = "René Fritze"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = clangquill.__version__
# The full version, including alpha/beta/rc tags.
release = clangquill.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output -------------------------------------------

html_theme = "furo"
html_theme_options = {}
# Custom sidebar templates, maps document names to template names.
# all: "**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]
# refer to https://github.com/pradyunsg/furo/blob/main/src/furo/theme/furo/theme.conf
# for available ones
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/scroll-end.html",
        "sidebar/variant-selector.html",
    ]
}

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


autoapi_python_use_implicit_namespaces = True
autoapi_dirs = [root_dir / 'src'/ 'clangquill']
autoapi_type = 'python'
# allows incremental build
autoapi_keep_files = True
autoapi_template_dir = this_dir / '_templates' / 'autoapi'

# clangquill._core is a compiled nanobind extension, so AutoAPI's static
# analysis cannot resolve `from clangquill import _core`; that import-resolution
# warning is expected and would otherwise fail the warning-as-error docs build.
suppress_warnings = ["autoapi.python_import_resolution"]

coverage_ignore_modules = r"""
    """.split()
coverage_ignore_functions = r"""
    test($|_) (some|all)true bitwise_not cumproduct pkgload
    generic\.
    """.split()
coverage_ignore_classes = r"""
    """.split()

coverage_c_path = []
coverage_c_regexes = {}
coverage_ignore_c_items = {}

# autodoc_default_flags = ['members', 'undoc-members', 'show-inheritance']

# PyQt5 inventory is only used internally, actual link targets PySide2
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "PyQt5": ("https://www.riverbankcomputing.com/static/Docs/PyQt5", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    "matplotlib": ("https://matplotlib.org", None),
    "Sphinx": ("https://www.sphinx-doc.org/en/master/", None),
}


def linkcode_resolve(domain, info):
    if domain == "py":
        if not info["module"]:
            return None
        filename = info["module"].replace(".", "/")
        baseurl = "https://github.com/renefritze/clangquill"
        branch = os.environ.get("GITHUB_REF_NAME", "main")
        return f"{baseurl}/blob/{branch}/src/{filename}.py"
    return None
